# Generated by Django 4.2.3 on 2025-05-18 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='speed_bonus',
            field=models.IntegerField(default=0),
        ),
    ]
