# Generated by Django 4.2.3 on 2025-05-18 12:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_item_speed_bonus'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrimeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('min_level', models.PositiveIntegerField(default=1)),
                ('energy_cost', models.PositiveIntegerField(default=10)),
                ('min_cash_reward', models.PositiveIntegerField(default=100)),
                ('max_cash_reward', models.PositiveIntegerField(default=500)),
                ('min_exp_reward', models.PositiveIntegerField(default=10)),
                ('max_exp_reward', models.PositiveIntegerField(default=50)),
                ('jail_risk', models.FloatField(default=0.2)),
                ('min_jail_time', models.PositiveIntegerField(default=300)),
                ('max_jail_time', models.PositiveIntegerField(default=1800)),
                ('item_reward_chance', models.FloatField(default=0.1)),
                ('strength_factor', models.FloatField(default=0.0)),
                ('defense_factor', models.FloatField(default=0.0)),
                ('speed_factor', models.FloatField(default=0.0)),
                ('dexterity_factor', models.FloatField(default=0.0)),
                ('intelligence_factor', models.FloatField(default=0.0)),
                ('base_success_chance', models.FloatField(default=0.5)),
                ('possible_rewards', models.ManyToManyField(blank=True, related_name='crime_rewards', to='game.item')),
            ],
            options={
                'verbose_name': 'Crime Type',
                'verbose_name_plural': 'Crime Types',
                'db_table': 'game_crime_type',
            },
        ),
        migrations.CreateModel(
            name='CrimeResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('jailed', 'Player Jailed'), ('interrupted', 'Interrupted')], max_length=20)),
                ('cash_reward', models.PositiveIntegerField(default=0)),
                ('exp_reward', models.PositiveIntegerField(default=0)),
                ('jail_time', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('crime_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='game.crimetype')),
                ('item_reward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crime_results', to='game.item')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crimes', to='game.location')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crime_results', to='game.player')),
            ],
            options={
                'db_table': 'game_crime_result',
                'ordering': ['-created_at'],
            },
        ),
    ]
